package land.chipmunk.chipmunkmod.listeners;

import net.minecraft.network.packet.Packet;
import net.minecraft.text.Text;
import net.minecraft.util.math.Vec3d;

public interface Listener {
    default void packetReceived (final Packet<?> packet) { }

    default void packetSent (final Packet<?> packet) { }

    default void chatMessageReceived (final Text message) { }

    default void overlayMessageReceived (final Text message) { }

    default void coreReady () { }

    default void coreMoved () { }

    default void positionChanged (final Vec3d newPosition) { }
}
