package land.chipmunk.chipmunkmod.listeners;

import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.Packet;
import net.minecraft.world.phys.Vec3;

public interface Listener {
    default void packetReceived (final Packet<?> packet) { }

    default void packetSent (final Packet<?> packet) { }

    default void chatMessageReceived (final Component message) { }

    default void overlayMessageReceived (final Component message) { }

    default void coreReady () { }

    default void coreMoved () { }

    default void positionChanged (final Vec3 newPosition) { }

    default void timeUpdate () { }
}
